[package]
name = "brax"
version = "0.1.0"
edition = "2021"

[dependencies]
view = { path = "crates/view" }

[workspace]
members = [
    "crates/domain",
    "crates/usecase",
    "crates/gateway",
    "crates/infrastructure",
    "crates/utils",
    "crates/view",
    # presenter
]
