[package]
name = "brax"
version = "0.1.0"
edition = "2021"

[dependencies]

[workspace]
members = [
    "crates/domain",
    "crates/usecase",
    "crates/gateway",
    "crates/infrastructure",
    "crates/utils",
    "crates/view",
    # presenter
]
