[package]
name = "view"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.28.1"
log = { workspace = true }
strum = { workspace = true }
domain = { path = "../domain" }
